# Yalnizca adres degisirse burayi duzenleyip GitHub'a kaydet.
# Adres https:// ile baslamali; sonuna / ekleme.
EvDiziBox=https://www.dizibox.live
EvWebteIzle=https://webteizle.info
EvYabanciDizi=https://yabancidizi.news
EvDiziGom=https://www.dizigom.icu
EvSezonlukDizi=https://sezonlukdizi.cc
EvHDFilmCehennemi=https://www.hdfilmcehennemi.nl
EvFilmModu=https://filmmodu.live
EvKultFilmler=https://kultfilmler.net
EvRareFilmm=https://rarefilmm.com
EvDiziPal=https://dizipal1581.com
EvFilmMakinesi=https://filmmakinesi.to
EvFullHDFilmizlesene=https://www.fullhdfilmizlesene.now
